<?php

namespace FrontBundle\Repository;

/**
 * EventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getElencoCitta()
    {
        $results = $elencoSale = $this->getEntityManager()
        ->createQuery(
            'SELECT DISTINCT s.citta FROM FrontBundle:Sala s'
            )
        ->getResult();
        $data = [];
        foreach ($results as $result) {
            $data[$result['citta']] = $result['citta'];
        }
        return $data;
    }
}
