<?php

namespace FrontBundle\Repository;

/**
 * Evento_SalaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Evento_SalaRepository extends \Doctrine\ORM\EntityRepository
{
}
