<?php

namespace FrontBundle\Repository;

/**
 * Evento_UtentiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Evento_UtentiRepository extends \Doctrine\ORM\EntityRepository
{
}
