<?php
namespace FrontBundle\Repository;

use FrontBundle\Entity\Evento;

/**
 * EventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventoRepository extends \Doctrine\ORM\EntityRepository
{

    public function findBySala($sala)
    {
        return $this->getEntityManager()
        ->createQuery(
            'SELECT
            s
            FROM FrontBundle:Sala s'
            )
        ->setParameter('sala', $sala)
 
        ->getResult();
    }

    public function getElencoSala()
    {
        $results = $elencoEventi = $this->getEntityManager()
        ->createQuery(
            'SELECT DISTINCT s.nome FROM FrontBundle:Sala s'
            )
        ->getResult();
        $data = [];
        foreach ($results as $result) {
            $data[$result['nome']] = $result['nome'];
        }
        return $data;
    }
}