<?php

namespace FrontBundle\Repository;

/**
 * invitatiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class invitatiRepository extends \Doctrine\ORM\EntityRepository
{
}
