<?php
namespace FrontBundle\Repository;


/**
 * SalaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByMinPosti($numeroPosti, $citta)
    {
        return $this->getEntityManager()
        ->createQuery(
            'SELECT
            s
            FROM FrontBundle:Sala s
            WHERE  s.posti >= :posti AND s.citta = :citta'
            )
        ->setParameter('posti', $numeroPosti)
        ->setParameter('citta', $citta)

        ->getResult();
    }

    public function getElencoCitta()
    {
        $results = $elencoSale = $this->getEntityManager()
        ->createQuery(
            'SELECT DISTINCT s.citta FROM FrontBundle:Sala s'
            )
        ->getResult();
        $data = [];
        foreach ($results as $result) {
            $data[$result['citta']] = $result['citta'];
        }
        return $data;
    }
}
