user:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

fos_registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /register

fos_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /profile
