user:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"