front_login:
    path:     /
    defaults: { _controller: FrontBundle:Login:login }

front_user:
    path:     /user
    defaults: { _controller: FrontBundle:User:user }

front_sala:
    path:     /sala
    defaults: { _controller: FrontBundle:Sala:sala }

front_lista_sale:
    path:     /lista_sale
    defaults: { _controller: FrontBundle:Sala:listasale }

front_lista_eventi:
    path:     /lista_eventi
    defaults: { _controller: FrontBundle:Eventi:eventi }

front_lista_users:
    path:     /lista_users
    defaults: { _controller: FrontBundle:User:listausers }
