front_lista_users:
    path:     /lista_users
    defaults: { _controller: FrontBundle:User:list }

front_user:
    path:     /
    defaults: { _controller: FrontBundle:User:user }

front_user_modifica:
    path:     /utente/{id}/edit
    defaults: { _controller: FrontBundle:User:edit}


####################
front_lista_sale:
    path:     /lista_sale
    defaults: { _controller: FrontBundle:Sala:list }

front_sala:
    path:     /sala/{id}
    requirements:
        id: \d+
    defaults: { _controller: FrontBundle:Sala:sala }

front_sala_crea:
    path:     /sala/new
    defaults: { _controller: FrontBundle:Sala:create }

front_sala_modifica:
    path:     /sala/{id}/edit
    defaults: { _controller: FrontBundle:Sala:edit }

front_sala_delete:
    path:     /sala/{id}/delete
    requirements:
        id: \d+
    defaults: { _controller: FrontBundle:Sala:delete}
####################


front_lista_eventi:
    path:     /lista_eventi
    defaults: { _controller: FrontBundle:Eventi:list }

front_crea_evento:
    path:     /evento/create
    defaults: { _controller: FrontBundle:Eventi:create }
