front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

front_user:
    path:     /user
    defaults: { _controller: FrontBundle:User:user }

front_sala:
    path:     /sala
    defaults: { _controller: FrontBundle:Sala:sala }

